" require config
runtime! config/**/*.vim

" Settings
set nocompatible
set visualbell
set number
set laststatus=2
syntax on
set background=dark

" Filetypes
filetype off
filetype plugin indent on


" Indentation
set expandtab
set smarttab
set autoindent
set shiftwidth=2
set softtabstop=2
set splitbelow

" Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

" Custom plugins
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'bling/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'tpope/vim-fugitive'
Plugin 'altercation/vim-colors-solarized'

call vundle#end()

" Colorscheme
colorscheme solarized

