"
" General settings
"

" Required options
set nocompatible
filetype plugin on

" Various settings
syntax on
set visualbell
set number
set laststatus=2
set nowrap
set ttimeoutlen=50 " Fix delay at mode change
set updatetime=250 " Fix delay at mode change
set mouse=a

" Remove duplicate information in status bar
set noshowcmd
set noshowmode

" Use spaces for indendation
set expandtab
set shiftround
set shiftwidth=2
set tabstop=2

" Show extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

"
" Plugin configuration
"

" Load pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

" Set up theme
colorscheme solarized
set background=dark

" vim-airline
let g:airline_theme = 'solarized'
let g:airline_solarized_bg = 'dark'
let g:airline_powerline_fonts = 1
let g:airline#extensions#ctrlp#color_template = 'normal'
let g:airline#extensions#tmuxline#enabled = 0

" vim-tmuxline
let g:tmuxline_preset = {
  \'a': '#T',
  \'win': ['#I', '#W'],
  \'cwin': ['#I', '#W'],
  \'z': '%R',
  \'options': {
    \'status-justify': 'right'}
  \}

