" Required options
set nocompatible
filetype plugin on

" Settings
set visualbell
set number
set laststatus=2
syntax on
set ttimeoutlen=50

" Load pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

"
" General settings
"

" Remove duplicate information in status bar
set noshowcmd
set noshowmode

" Set up colors
set t_Co&
set background=dark
let base16colorspace = 256

colorscheme base16-spacemacs

" Show line numbers
set number

" Use spaces for indendation
set expandtab
set shiftround
set shiftwidth=2
set tabstop=2

" Show extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·


"
" Plugin configuration
"

" vim-airline
let g:airline_theme = 'base16_spacemacs'
" let g:airline_powerline_fonts = 1
let g:airline#extensions#ctrlp#color_template = 'normal'
let g:airline#extensions#tmuxline#enabled = 0

" vim-tmuxline
let g:tmuxline_preset = {
  \'a': '#T',
  \'win': ['#I', '#W'],
  \'cwin': ['#I', '#W'],
  \'z': '%R',
  \'options': {
    \'status-justify': 'right'}
  \}
