"
" General settings
"

" Required options
set nocompatible
filetype plugin on

" Various settings
syntax on
set visualbell
set t_vb= " Disable visualbell
set number
set cursorline
set laststatus=2
set nowrap
set ttimeoutlen=50 " Fix delay at mode change
set updatetime=250 " Fix delay at mode change
set ttyfast " Assume fast terminal connection
set autoread " Auto reload if file saved externally

" Mouse settings
set mouse=a " Enable mouse
set mousehide " Hide mouse while typing

" Remove duplicate information in status bar
set noshowcmd
set noshowmode

" Use spaces for indendation
set expandtab
set shiftround
set shiftwidth=2
set tabstop=2

" Show extra whitespace
set list listchars=tab:»·,trail:·,nbsp:·

"
" Plugin configuration
"

" Load pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
call pathogen#infect()
call pathogen#helptags()

" Set up theme
set background=dark

" Syntastic configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Syntastic checkers
let g:syntastic_dockerfile_checkers = ['hadolint']
let g:syntastic_python_checkers = ['pylint']

" Syntastic checkers options
let g:syntastic_sh_shellcheck_args="-x"

" vim-airline
let g:airline_solarized_bg = 'dark'
let g:airline_powerline_fonts = 0
let g:airline#extensions#ctrlp#color_template = 'normal'
let g:airline#extensions#tmuxline#enabled = 0

" vim-tmuxline
let g:tmuxline_preset = {
  \'a': '#T',
  \'win': ['#I', '#W'],
  \'cwin': ['#I', '#W'],
  \'z': '%R',
  \'options': {
    \'status-justify': 'right'}
  \}

